server:
  port: ${SERVER_PORT:8091}

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url:      ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

feign:
  usuario:
    url: ${FEIGN_USUARIO_URL:http://localhost:8090}

jwt:
  secret:     ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

empleados:
  creados:
    queue: ${EMPLEADOS_CREADOS_QUEUE:empleados.creados.queue}

appDescription: ${APP_DESCRIPTION}
appVersion:     ${APP_VERSION}
